### ISSUE TITLE
Error multiple request to rebuild

### ISSUE THREAD

**Issue by FM-silla** [jbaumann/pio_and_stm32cubeide#7]
Hi, tnx for the script I was able to move from cubeIDE project to platformio using the automatic script but i get continously the rebuild popup and finally this error....do you know what can be the cause?

"Error: Multiple requests to rebuild the project "STM32G4" index have been received! Automatic index rebuilding process has been terminated for 10 minutes. "

**Comment by jbaumann** [comment]
This seems to be a problem with the Intellisense index. 

See this issue: https://github.com/platformio/platformio-vscode-ide/issues/2363

The script does not change _libdeps_dir_, could you check whether another plug-in might be changing it and triggering the rebuild?

You could also try a manual rebuild as described in the issue. I would be interested if that fixes the problem.

**Comment by FM-silla** [comment]
> This seems to be a problem with the Intellisense index.
> 
> See this issue: [platformio/platformio-vscode-ide#2363](https://github.com/platformio/platformio-vscode-ide/issues/2363)
> 
> The script does not change _libdeps_dir_, could you check whether another plug-in might be changing it and triggering the rebuild?
> 
> You could also try a manual rebuild as described in the issue. I would be interested if that fixes the problem.

thanks I will investigate and let you know if I find smthig.
