### ISSUE TITLE
error of redefinition

### ISSUE THREAD

**Issue by Xinyu-Sheng** [jbaumann/pio_and_stm32cubeide#8]
I am a beginner with PlatformIO. Following your script, I encountered an error of redefinition during linking. Is it due to my personal reason? What are the possible solutions?

```
.pio/build/black_f407zg/src/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o: In function `HAL_DeInit':
stm32f4xx_hal.c:(.text.HAL_DeInit+0x0): multiple definition of `HAL_DeInit'
.pio/build/black_f407zg/FrameworkHALDriver/Src/stm32f4xx_hal.o:stm32f4xx_hal.c:(.text.HAL_DeInit+0x0): first defined here
.pio/build/black_f407zg/src/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o: In function `HAL_Init':
stm32f4xx_hal.c:(.text.HAL_Init+0x0): multiple definition of `HAL_Init'
```

**Comment by jbaumann** [comment]
This looks as if somehow the framework files are used twice, which is strange. Which version of the STM32CubeIDE and PlatformIO are you using?
Does your code compile in the STM32CubeIDE? And could you maybe attach the part of your project that produces this problem (please strip it down to the absolute minimum that produces the problem)?

**Comment by Sheng-Xinyu** [comment]
I generated the entire project using CubeMX, and added platformio.ini and setup_cubemx_env_auto.py in the project folder. After compilation, the project structure is as follows:
![image](https://user-images.githubusercontent.com/74916624/234726161-d70ea0dd-e966-4a16-9223-9652fb61522b.png)
I believe that during the build process, similar target files were generated in the pio/build folder for FrameworkHALDriver and src, one from the driver generated by CubeMX and the other from PlatformIO. I am using Win11 environment with PIO version 6.1.6 and CubeMX version 6.7.0.

**Comment by Xinyu-Sheng** [comment]
I generated the entire project using CubeMX, and added platformio.ini and setup_cubemx_env_auto.py in the project folder. After compilation, the project structure is as follows:
![image](https://user-images.githubusercontent.com/74916624/234726161-d70ea0dd-e966-4a16-9223-9652fb61522b.png)
I believe that during the build process, similar target files were generated in the pio/build folder for FrameworkHALDriver and src, one from the driver generated by CubeMX and the other from PlatformIO. I am using Win11 environment with PIO version 6.1.6 and CubeMX version 6.7.0.

**Comment by Xinyu-Sheng** [comment]
I think I found the issue. If I want to use the libraries from cubemx, I should use automatic_cubemx instead of automatic_pio!

**Comment by jbaumann** [comment]
Excellent. Can I close the issue then?

**Comment by Xinyu-Sheng** [comment]
Yes, and thank you for your work!
